# -*- coding: utf-8 -*-
"""Ingest report generation (HTML/JSON)."""

from __future__ import annotations

import os
import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ramses_ingest.publisher import IngestResult


def generate_html_report(results: list[IngestResult], output_path: str, studio_name: str = "Ramses Studio") -> bool:
    """Generate a professional HTML manifest of the ingest session."""
    
    # Simple CSS for a clean look
    css = """
    body { font-family: sans-serif; background: #f5f5f5; color: #333; padding: 20px; }
    .report { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-top: 0; }
    .studio-header { font-size: 12px; font-weight: bold; color: #0e639c; text-transform: uppercase; margin-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { text-align: left; background: #f8f9fa; padding: 12px; border-bottom: 2px solid #dee2e6; color: #666; font-size: 13px; }
    td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
    .status-ok { color: #27ae60; font-weight: bold; }
    .status-fail { color: #c0392b; font-weight: bold; }
    .status-warn { color: #f39c12; font-weight: bold; }
    .meta { color: #7f8c8d; font-size: 12px; margin-bottom: 20px; }
    .footer { margin-top: 40px; font-size: 12px; color: #95a5a6; text-align: center; }
    """

    rows = []
    for res in results:
        if not res or not res.plan:
            continue

        status_cls = "status-ok" if res.success else "status-fail"
        
        if res.success:
            status_text = "PASSED"
        elif "skipped" in (res.error or "").lower():
            status_text = "SKIPPED"
            status_cls = "status-warn"
        else:
            status_text = "FAILED"
        
        # Robust ID retrieval
        seq = getattr(res.plan, 'sequence_id', "—") or "—"
        shot = getattr(res.plan, 'shot_id', "—") or "—"
        step = getattr(res.plan, 'step_id', "—") or "—"
        
        row_html = f"""
        <tr>
            <td>{seq} / {shot}</td>
            <td>{step}</td>
            <td class="{status_cls}">{status_text}</td>
            <td>{res.frames_copied} fr</td>
            <td><code>{res.published_path or res.error or "N/A"}</code></td>
        </tr>
        """
        rows.append(row_html)

    if not rows:
        rows.append("<tr><td colspan='5' style='text-align:center; padding:20px; color:#999;'>No clips processed in this session.</td></tr>")

    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    year = time.strftime("%Y")
    project = "Unknown"
    if results and results[0].plan:
        project = getattr(results[0].plan, 'project_name', "") or results[0].plan.project_id or "Unknown"

    # Assemble HTML without a single giant f-string to prevent brace confusion
    html_parts = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        '    <meta charset="utf-8">',
        f"    <title>Ingest Report - {project}</title>",
        f"    <style>{css}</style>",
        "</head>",
        "<body>",
        '    <div class="report">',
        f'        <div class="studio-header">{studio_name}</div>',
        "        <h1>Ingest Manifest</h1>",
        '        <div class="meta">',
        f"            <strong>Project:</strong> {project}<br>",
        f"            <strong>Date:</strong> {timestamp}<br>",
        f"            <strong>Total Clips:</strong> {len(results)}",
        "        </div>",
        "        <table>",
        "            <thead>",
        "                <tr>",
        "                    <th>Shot ID</th>",
        "                    <th>Step</th>",
        "                    <th>Verification</th>",
        "                    <th>Count</th>",
        "                    <th>Destination</th>",
        "                </tr>",
        "            </thead>",
        "            <tbody>",
        "".join(rows),
        "            </tbody>",
        "        </table>",
        '        <div class="footer">',
        f"            &copy; {year} {studio_name} &bull; Generated by Ramses-Ingest",
        "        </div>",
        "    </div>",
        "</body>",
        "</html>"
    ]
    
    html = "\n".join(html_parts)

    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return True
    except Exception:
        return False